### ISSUE TITLE
Suggestion: add sent id to naf.sentences and naf.paragraphs

### ISSUE THREAD

**Issue by AnnickvOol** [wjwillemse/nafigator#9]
* nafigator version: 0.1.45
* Python version: 3.8.8
* Operating System: Windows

### Description

For analyses it would be useful if naf.sentences and naf.paragraphs also contain the sentence id(s) (similar to naf.text). Currently, naf.sentences and naf.paragraphs contain the paragraph id and page id but not the sentence id(s). 

### What I Did

Add sent to the sentences property and paragraphs property in nafdocument.py.

**Comment by wjwillemse** [comment]
This was added to v0.1.46. Properties naf.sentences and naf.paragraphs now contain 'sent' in the dictionary which is a list of sentence ids. Please put issues on github/DeNederlandscheBank/nafigator, from where nafigator is currently maintained.
